### ISSUE TITLE
No output was found

### ISSUE THREAD

**Issue by abdulfasithnpm** [incogbyte/jsearch#1]
i just a command
"python3 jsearch.py -u https://yyy.com -n yyy" after this command 
>> Create directory yyy.com
>> File will be saved at yyy.com
but no output for this domain.

**Comment by devcoinfet** [comment]
I am addressing tht myself I ran int othat on 1/2 urls last night if i solve it i'll do a pull asap

**Comment by incogbyte** [comment]
> I am addressing tht myself I ran int othat on 1/2 urls last night if i solve it i'll do a pull asap

Done my friend =)
